### ISSUE TITLE
Opt out of snippet expansion

### ISSUE THREAD

**Issue by xsh005** [nvimdev/epo.nvim#6]
Sometimes I do not want to use snippets when completing items, for instance

```lua
vim.tbl_map(my_func)
```

now say I have `my_function` as a complete item, in this case I do not want snippets to complete the args since I am passing the function itself as an argument, but even if I don't complete and manually type out `my_function` and press `,` the snippet still triggers, despite me not pressing `<C-y>`

**Comment by glepnir** [comment]
CTRL_Y mean confrim use CTRL_E

**Comment by xsh005** [comment]
Makes sense, but what I mean is whether there is a way to only expand snippets when I do a `<C-y>` (explicitly ask for completion)? Seems more ergonomic.

**Comment by glepnir** [comment]
maybe need split cr and c-y.

**Comment by xsh005** [comment]
what do you mean?
